### ISSUE TITLE
Configuration is not saved

### ISSUE THREAD

**Issue by kaczuss** [cronn-de/validation-files-comparison-intellij-plugin#1]
Hi

Configuration is not saved and after IntelliJ IDEA restart is reset.

My version of IntelliJ is:

IntelliJ IDEA 2019.2.1 (Ultimate Edition)
Build #IU-192.6262.58, built on August 20, 2019
Runtime version: 11.0.3+12-b304.39 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 5.0.0-25-generic

**Comment by aykborstelmann** [comment]
Thanks for spotting this issue!

I found the issue, there were some fields with wrong access modifier. 
I made a pull request which will fix this issue.

**Comment by kaczuss** [comment]
Many thanks for very fast fix. It works great.
