### ISSUE TITLE
Feature request: Navigate from test method to validation file and back

### ISSUE THREAD

**Issue by pfhartma** [cronn-de/validation-files-comparison-intellij-plugin#18]
It would be a huge improvement for the workflow of our team, if you could quickly navigate from the test method to the corresponding validation file (and back).

## Example including nested tests and parameters:
```java
class PaymentIntegrationTest extends BaseIntegrationTest {
    @Nested
    class PaymentGeneration {
        @Nested
        @SkipResetsBeforeEachTest
        class GetPayments {
            @ParameterizedTest
            @MethodSource("searchPaymentsTestParams")
            void testGetPayments_sorted(PaymentSortField sortField, SortDirection sortDirection) throws Exception {
	            ...
                compareActualWithValidationFile(response, suffix);
            }
        }
    }
}
```
### Idea for the workflow
I would like to place the cursor on `testGetPayments_sorted`, press a shortcut, then:
* Open the first file matching `data/test/validation/PaymentIntegrationTest/PaymentGeneration/GetPayments/testGetPayments_sorted*`
* Possibly: Offer a list of all such files for selection, in case there is more than one

Reverse direction: With the validation file selected in the project pane or opened in the editor, press a shortcut and jump to the corresponding test method.

## `validation` directory vs. `output` directory
After running the test, one might want to see the file in the output directory, rather than the validation directory. However, I find a situation much more frequent where I just want to read and understand a test, without the need to run it locally.

In any case, the info regarding `output` directory can be found by opening the diff window.

**Comment by kevin-keul** [comment]
Published with plugin version 2.1
