### ISSUE TITLE
Please provide update for IntelliJ IDEA 2019.3

### ISSUE THREAD

**Issue by tobiasgradl** [cronn-de/validation-files-comparison-intellij-plugin#3]
After updating IntelliJ IDEA to 2019.3 I get the following message:
> **Plugin Error**
> Plugin "Validation-File Comparison" is incompatible (target build range is 192.5728 to 192.*).

Can you release an update that is compatible with the latest IntelliJ version?

Thanks in advance for considering!

:wave:

**Comment by aykborstelmann** [comment]
Thanks for reporting this issue. 

Yes, I've seen this message before. I will have a look at this soon.
